default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: language_DB

test:
  <<: *default
  database: language_DB

production:
  <<: *default
  database: language_DB
  username: root
  password:
